{% set name = "qdoas2harp" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UVVIS-BIRA-IASB/qdoas2harp/archive/refs/tags/{{ version }}.tar.gz
  sha256: b001e169e2e429a04ab58d2de2b94d6aee4707b430620e3cea7d9582813389fc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - qd2hp = qdoas2harp.convert2harp:cml
    - aux_imp = qdoas2harp.importer_aux:cml

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - attrs
    - cattrs
    - netCDF4
    - numpy

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/UVVIS-BIRA-IASB/qdoas2harp
  summary: 'converts qdoas output format into a HARP compliant format'
  description: |
    qdoas2harp is a tool that converts the qdoas output format into a HARP compliant format.
    This aids in the further analysis of the qdoas results.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://uvvis-bira-iasb.github.io/qdoas2harp/
  dev_url: https://github.com/UVVIS-BIRA-IASB/qdoas2harp

extra:
  recipe-maintainers:
    - svniemeijer
