{% set name = "qdoas2harp" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UVVIS-BIRA-IASB/qdoas2harp/archive/refs/tags/{{ version }}.tar.gz
  sha256: bf48910d085aa8633e144c069987cdcf9c60e0b87dc9286d74b8cf9401b69b9d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - qd2hp = qdoas2harp.convert2harp:cml
    - aux_imp = qdoas2harp.importer_aux:cml

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - attrs
    - cattrs
    - netCDF4
    - numpy

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/UVVIS-BIRA-IASB/qdoas2harp
  summary: 'converts qdoas output format into a HARP compliant format'
  description: |
    qdoas2harp is a tool that converts the qdoas output format into a HARP compliant format.
    This aids in the further analysis of the qdoas results.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://uvvis-bira-iasb.github.io/qdoas2harp/
  dev_url: https://github.com/UVVIS-BIRA-IASB/qdoas2harp

extra:
  recipe-maintainers:
    - svniemeijer
